### ISSUE TITLE
Sheep 5.0.0 To-Do List

### ISSUE THREAD

**Issue by KnownUnown** [KnownUnown/Sheep#8]
Sheep 4.x.x really sucks. Everything was implemented in a spontaneous manner, with no thought given to usability and clean code. Essential features were missing. A redesign is in order.
- [x] Lay down framework for classes / API
- [x] Implement new Source system for plugin sources, such as PocketMine Forums, URL, Filesystem
- [x] Implement Plugin with async, callbacks (`install`, `uninstall`, `fetch`, etc)
- [x] Implement dependency fetching (kinda)
- [x] Implement plugin updates
